### ISSUE TITLE
Fix rev 6.3 and add current

### ISSUE THREAD

**Issue by michalszmidt** [vmactions/openbsd-vm#12]
Hi!

I need to compile rust on OpenBSD.
I can't install toolchain using rustup as it's not available, so I used one from repo.
The problem is it is way to old to compile my app.

People suggested using openbsd-current branch.

Could you add support for it?
It doesn't seem to be a lot of work, as snapshots, including `iso`, are provided here: https://cdn.openbsd.org/pub/OpenBSD/snapshots/amd64/

AFAIK, this would be something like creation of `openbsd-current.conf` with  changed `VM_ISO_LINK="https://cdn.openbsd.org/pub/OpenBSD/snapshots/amd64/install73.iso"` in conf dir of [vmactions/openbsd-builder](https://github.com/vmactions/openbsd-builder) and possibly changing the VM_RSYNC_PKG version.

This may be a workaround for #11 compilation errors

Thanks in advance!

**Comment by Neilpang** [comment]
the  latest  openbsd 7.3  was not built successfully. 

The intaller of openbsd is  fragile or buggy,  it always panics.

**Comment by michalszmidt** [comment]
Yeah, that's right...

I forked vmactions/openbsd-builder repository and experimented with [openbsd-current.conf](https://github.com/michalsHoweverzmidt/openbsd-builder/blob/main/conf/openbsd-current.conf) and [openbsd-current.opts.txt](https://github.com/michalszmidt/openbsd-builder/blob/main/conf/openbsd-current.opts.txt) without success.

Did you know that [OpenBSD supports loading answers from text file](https://stackoverflow.com/questions/67163951/is-there-an-automatic-way-to-create-an-install-conf-for-openbsd-autoinstall)?

Maybe instead of answering installer question in real-time, we can prepare file, copy to vm and load?

**Comment by michalszmidt** [comment]
Ok, so tried to play with that.

File must be fetched without curl or wget, so probably `ftp` binary can be used to obtain file from fqdn, as it works also with https.

After VM goes up, _it needs to have working network_, then:

```bash
Welcome to OpenBSD installer ((I)nstall ...; String S; enter;
string ftp https://raw.githubusercontent.com/.../installer.resp; enter;
string mv installer.resp /tmp/i/install.resp; enter;
sting autoinstall; enter;
Install or Upgrade; string I; enter
```

where installer.resp is like this
```conf
System hostname = openbsd
Network interface to configure = em0
IPv4 address for em0 = autoconf
IPv6 address for em0 = none
Network interface to configure = done
Password for root account = $2b$10$qS3/zFLn/6wTQrjNhAddEepvKw.XculyRsXH60FLXjcj5fQeZzIQu
Start sshd(8) by default = yes
Do you expect to run the X Window System = no
Change the default console to com0 = no
Setup a user = no
Allow root ssh login = yes
Which disk is the root disk = wdO
Encrypt the root disk = no
Use (W)hole disk MBR, whole disk (G)PT or (E)dit = whole
Use (A)uto layout, (E)dit auto layout, or create (C)ustom layout = a
Location of sets = http
HTTP proxy URL = none
HTTP Server = cdn.openbsd.org
Server directory = pub/OpenBSD/snapshots/amd64
Set name(s) = done
Location of sets = done
What timezone are you in = UTC
Exit to (S)hell, (H)alt or (R)eboot = R
```

AFAIK this configuration misses question about keyboard layout.Rest should work.

password for root account is `printf '%s' 'openbsd' | encrypt` as suggested [here](https://www.codemadness.org/openbsd-autoinstall.html)

Could you help with that? You can do a PR on my already modified fork not to bloat your repo, or just create another branch on your.

**Comment by Neilpang** [comment]
good job. I will play with it

**Comment by Neilpang** [comment]
I just added a new branch resp to use the resp file from your post:

https://github.com/vmactions/openbsd-builder/tree/resp

but it seems that the autoinstall is crashing .

Can you please fix it more ?

**Comment by michalszmidt** [comment]
I saw you replaced opts file with install.resp file. This won't work.
install.resp file must be placed inside vm just after start.
we need opts file so it could answer at least the first question, to be able to drop into shell, to download file and place it into `/tmp/i/`

I have very little experience with virtualbox and its automated install magic, so I dunno the easiest way of placing external file into vm. 
On KVM/XEN I would mount dir with virtiofs, download it from web or prepare ISO archive with this file and mount it inside.

Additionally I'm not sure if all questions from installer are answered.

Let me experiment with this.

**Comment by Neilpang** [comment]
you can run the  manual.yml  action to debug:

https://github.com/vmactions/openbsd-builder/actions/workflows/manual.yml

**Comment by Neilpang** [comment]
you can add a "NGROK_TOKEN" secret to the repo, and then you can get a vnc connection from ngrok.com

**Comment by Neilpang** [comment]
It's blocking at the last step:
![image](https://github.com/vmactions/openbsd-vm/assets/8305679/8147e67c-13a6-4efd-acab-e5d0a708c505)

**Comment by michalszmidt** [comment]
Hmm. No idea.

Maybe we can ask for help someone from OpenBSD team?

**Comment by Neilpang** [comment]
It's random issue.  99% blocking,  1% success.

I don't know anyone from OpenBSD team.

**Comment by mirabilos** [comment]
> the latest openbsd 7.3 was not built successfully.
>
> The intaller of openbsd is fragile or buggy, it always panics.

Could be because you use VirtualBox. I’ve had nothing but trouble with that and MirBSD (so bad I blacklisted it in the installer), and I talked with one of the developers at LinuxTag many years ago, who told me they’re aware of the bugs but only get money/tasks to fix Windows and Linux bugs.

**Comment by michalszmidt** [comment]
@mirabilos So you suggest to drop VirtualBox?

Dunno whether Linux runner has nested virtualization enabled. 
If yes, we could convert all this to kvm. But it seems to be a huge amount of work...

I have another proposition.
Take a look at [CirrusCI custom VMs](https://cirrus-ci.org/guide/custom-vms/). 

> Already things like [Docker Builder](https://cirrus-ci.org/guide/docker-builder-vm/) and [freebsd_instance](https://cirrus-ci.org/guide/FreeBSD/) are basically a syntactic sugar for launching Compute Engine instances from a particular limited set of images.
> We recommend to use [Packer](https://www.packer.io/) for building your custom images. As an example, please take a look at [our Packer templates](https://github.com/cirruslabs/osx-images) used for building Docker Builder VM image. After building your image, please make sure [the image publicly available](https://cloud.google.com/compute/docs/images/managing-access-custom-images#share-images-publicly):

Cirrus integrates well with gh for free. I commonly use both CI systems.
Anyway my point is that gh is not prepared for custom VMs but Cirrus is.
Maybe it's worth to follow their instructions?

What do you think?

**Comment by michalszmidt** [comment]
> It's random issue. 99% blocking, 1% success.
> 
> I don't know anyone from OpenBSD team.

@jcs Maintains [OpenBSD](https://github.com/openbsd) organization, maybe we can ask him to contact other OpenBSD maintainers?

It's hard to say if this is Virtualbox that fails or OpenBSD automated Installer problem.

**Comment by mirabilos** [comment]
Michał Szmidt dixit:

>@mirabilos So you suggest to drop VirtualBox?

I’m just pointing out that it may be part of the troubles causer.

>Dunno whether Linux runner has nested virtualization enabled.

It’s probably some kind of container. But might be worth to check.

>If yes, we could convert all this to kvm.
>But it seems to be a huge amount of work...

You don’t have to do them all at once.

But it would have the benefit that you can use kpartx and mount
to access most guests’ filesystems, so you can copy stuff there
before booting it (both the checkout and possibly cached extra
packages or something).

>I have another proposition.
>Take a look at [CirrusCI custom VMs](https://cirrus-ci.org/guide/custom-vms/).
[…]
>Cirrus integrates well with gh for free. I commonly use both CI systems.
>Anyway my point is that gh is not prepared for custom VMs but Cirrus is.
>Maybe it's worth to follow their instructions?

I had never heard of them before yet. Maybe, if they work?
I’ll keep them in mind for when I have some time to spend
to look into that again.

Thanks,
//mirabilos
-- 
> Hi, does anyone sell openbsd stickers by themselves and not packaged
> with other products?
No, the only way I've seen them sold is for $40 with a free OpenBSD CD.
	-- Haroon Khalid and Steve Shockley in gmane.os.openbsd.misc

**Comment by Neilpang** [comment]
I'm planning to rewrite this project with raw kvm(virtualbox is not good).
A prototype is already working for me.  It will be able to run on either Mac runner or Linux runner.

Anyone who are interested, please keep an eye on this project.

**Comment by michalszmidt** [comment]
> I'm planning to rewrite this project with raw kvm(virtualbox is not good). A prototype is already working for me. It will be able to run on either Mac runner or Linux runner.
> 
> Anyone who are interested, please keep an eye on this project.

So cool!

A few questions:
- Would it be possible then to add support for aarch64 with qemu?
- Could you [add support for Solaris successor](https://github.com/vmactions/solaris-vm/issues/34) that is Illumos (OpenIndiana/OmniOS)

**Comment by Neustradamus** [comment]
To follow

**Comment by Neilpang** [comment]
The  new `openbsd-vm:v1` is totalled rewritten.
I'm checking to support the current.  just wait.

**Comment by Neilpang** [comment]
BTW, the 7.3 is already suported.

**Comment by Neilpang** [comment]
7.4 is supported.
