### ISSUE TITLE
Errors with copy back of files using rsync

### ISSUE THREAD

**Issue by lcheylus** [vmactions/openbsd-vm#16]
I created a GH workflow with `vmactions/openbsd-vm` v1.0.4 to run a job (build of a Rust project on OpenBSD 7.4/stable).

I'm using rsync to sync files between OpenBSD guest and Ubuntu host (GH runner):
```
with:
  sync: rsync
```

At the end of my workflow, I want to copy back files from the OpenBSD guest to the Ubuntu host => `copyback: false` is not defined in my job.

Errors occurs at the end of my job to copy files back from the VM:
```
Copy files back from the VM
  get back by rsync
  /usr/bin/bash /home/runner/work/_actions/vmactions/openbsd-vm/v1.0.4/run.sh rsyncBackFromVM
  Config file: openbsd-7.4.conf
  Permission denied, please try again.
  Permission denied, please try again.
  root@192.168.122.215: Permission denied (publickey,password,keyboard-interactive).
  rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
  rsync error: unexplained error (code 255) at io.c(231) [Receiver=3.2.7]
  Error: The process '/usr/bin/bash' failed with exit code 255
```
=> errors with SSH connection from OpenBSD VM to guest when running rsync.

See my workflow logs https://github.com/lcheylus/cargo-nextest-openbsd/actions/runs/7428205763 for details.

**Comment by Neilpang** [comment]
can you please try to run it again?  Is that just a random error?

My test is working well:
https://github.com/vmactions/openbsd-vm/actions/runs/7430759846/job/20220798176

**Comment by lcheylus** [comment]
It's not a random error, same logs with "Copy files back from the VM" during a new try for my job => https://github.com/lcheylus/cargo-nextest-openbsd/actions/runs/7430800108/job/20220876993

**Comment by Neilpang** [comment]
I just made a new release,  please try with the new release.

**Comment by lcheylus** [comment]
Same errors with vmactions/openbsd-vm@v1.0.5 during "Copy files back from the VM" => https://github.com/lcheylus/cargo-nextest-openbsd/actions/runs/7430893869/job/20221084790

I don't understand your fix in v1.0.5 : where are the changes in base-vm (minor fix)?

**Comment by Neilpang** [comment]
try with the latest version

**Comment by lcheylus** [comment]
**NOK with vmactions/openbsd-bsd v1.0.6**, see my last test => https://github.com/lcheylus/cargo-nextest-openbsd/actions/runs/7433193219/job/20225905183

Download a tar.gz file in OpenBSD VM with curl and copyback to Linux host => always the same errors with "Permission denied" for SSH connection/rsync.

**Please, be more precise in your commit logs for your fix**: "minor fix/try with the last version" is not very constructive and helpful to help you to debug and fix an issue.

**Comment by lcheylus** [comment]
Problem solved using user `root` in OpenBSD VM => files are correctly copied back from VM to Ubuntu host at the end of job.

See my workflow with tests => https://github.com/lcheylus/cargo-nextest-openbsd/actions/runs/7433787501/job/20227215535
